defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

hydra:
  job:
    chdir: False

#continue:
saved_checkpoint : False
checkpoint_path :

data:
  data_path: "/sdcc/u/smccue/projects/inr_sampling/scent_data/1k"
  data_type: mmap
  mmap_dir: '/sdcc/u/smccue/projects/inr_sampling/mmap_save'
  dataset_name: "shallow-water-dino" 
  data_to_encode:
  missing_rate:
  ntrain : 
  ntest : 
  sub_from :
  space_factor : 1 # space resolution
  time_factor : 1
  seed: 15
  val_missing_rate: 0.0
  sub_array_num: 1
  split_ratios:
    - 0.7
    - 0.15
    - 0.15

optim:
  batch_size: 32
  batch_size_val: 
  lr_inr : 0.000005
  lr_code : 0.01
  meta_lr_code : 0.000005
  weight_decay_code: 0
  inner_steps : 3
  epochs : 10000

inr:
  model_type : "siren"
  latent_dim : 256
  depth : 5
  hidden_dim : 256
  w0 : 30.0
  use_latent: True
  modulate_scale: False
  modulate_shift: True
  hypernet_depth: 1
  hypernet_width: 128
  last_activation: 
  loss_type: "mse"  # All below are for EVOS only
  use_lr_scheduler: "store_true"
  multi_data: "store_true"
  signal_type: "image"
  eval_lpips: "store_true"
  # Check if redundant
  hidden_layers: 3
  hidden_features: 256
  first_omega: 30
  hidden_omega: 30
  first_bias_scale: None
  scale_req_grad: "store_true"
  N_freqs: 10
  scale: 30

wandb:
  use_wandb: False
  project: "functa2functa"
  name: 
  id: 
  sweep_id:

sampling:
  type: "random"
  rate: 0.2
  cluster_type: "slic"              # All below are for EVOS only
  sample_num_schedular: "constant"  # "constant", "linear", "step", "cosine", "reverse-cosine"
  lap_coff: 1e-5
  crossover_method: "select"
  use_laplace_epoch: 1500
  mutation_method: "constant"       # "constant", "linear", "exp"
  init_mutation_ratio: 0.5
  end_mutation_ratio: 0.5
  profile_interval_method: "lin_dec"    # "fixed", "lin_dec" 
  init_interval: 100
  end_interval: 50
  profile_guide: "value"            # "value", "diff_1"
  save_dir: "./log"
  tag: "exp"
  up_folder_name: "debug"
  debug: "store_true"
  device: "cuda:0"
  log_epoch: 500
  snap_epoch: 5000
  measure_dense_diff: "store_true"
  mdd_interval: 1
  measure_crossover_diff: "store_true"
  measure_sample_diff: "store_true"
  record_indices: "store_true"
  dense_measure_psnr: "store_true"
# data_folder=""

transform:
  transform: "min_max"
  trans_shift: -0.5
  trans_scale: 2.0
  pn_cum: 0.5
  pn_buffer: -1
  box_shift: 0.1
  pn_alpha: 0.01
  pn_k: 256.0
  pn_beta: 0.05
  gamma_boundary: 5.0
  gamma: 1.0
  inverse: "store_true"
  rpp: "store_true"
                                    

# sample type: random; NMT;
          