defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

hydra:
  job:
    chdir: False

#continue:
saved_checkpoint : False
checkpoint_path :

data:
  data_path: "/pscratch/sd/g/gzhao27/INR/data/NS2d/ns_mmap"
  data_type: mmap
  mmap_dir: '/pscratch/sd/g/gzhao27/INR/SOMA/results/soma_mmap_save'
  dataset_name: "shallow-water-dino" 
  data_to_encode:
  missing_rate:
  ntrain : 
  ntest : 
  sub_from :
  space_factor : 1 # space resolution
  time_factor : 1
  seed: 23
  val_missing_rate: 0.0
  sub_array_num: 1
  split_ratios:
    - 0.7
    - 0.15
    - 0.15

optim:
  batch_size: 32
  batch_size_val: 
  lr_inr : 0.000005
  lr_code : 0.01
  meta_lr_code : 0.000005
  weight_decay_code: 0
  inner_steps : 3
  epochs : 10000

inr:
  model_type : "siren"
  latent_dim : 256
  depth : 6
  hidden_dim : 256
  w0 : 30.0
  use_latent: True
  modulate_scale: False
  modulate_shift: True
  hypernet_depth: 1
  hypernet_width: 128
  last_activation: 
  loss_type: "mse"

wandb:
  use_wandb: False
  project: "functa2functa"
  name: 
  id: 
  sweep_id:

sampling:
  type: random
  rate: 0.2
  cluster_type: slic


# sample type: random; NMT; 