defaults:
  - _self_
  - data: null
  - optim: null
  - inr: null
  - wandb: null

hydra:
  job:
    chdir: False

data:
  dir: "/data/serrano/"
  data_path: '/global/cfs/cdirs/m4259/ecucuzzella/soma_ppe_data/ml_converted/month_1/thedataset-impliciBottomDrag.hdf5'
  mmap_dir: '/pscratch/sd/g/gzhao27/INR/SOMA/results/soma_mmap_save'
  dataset_name: "shallow-water-dino" 
  data_to_encode:
  ntrain : 
  ntest : 
  sub_from :
  space_factor : 2 # space resolution
  time_factor : 2
  seed: 23
  same_grid: True
  seq_inter_len : 20 
  seq_extra_len : 20
  missing_rate: 0.0
  val_missing_rate: 0.0
  sub_array_num: 1

optim:
  batch_size: 32
  batch_size_val: 
  lr_inr : 0.000005
  gamma_step : 0.9
  lr_code : 0.01
  meta_lr_code : 0.000005
  weight_decay_code: 0
  inner_steps : 3
  test_inner_steps : 3
  epochs : 10000

inr:
  model_type : "siren"
  latent_dim : 256
  depth : 6
  hidden_dim : 256
  w0 : 30
  use_latent: True
  modulate_scale: False
  modulate_shift: True
  hypernet_depth: 1
  hypernet_width: 128
  last_activation: 
  loss_type: "mse"

wandb:
  use_wandb: False
  entity: "spatiotemp-isir"
  project: "functa2functa"
  name: 
  id: 
  dir:
  sweep_id:
  saved_checkpoint : False
  checkpoint_path :

jz: 
  program: training/inr.py
  mode: dev
  partition: gpu_p2