#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=6:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --constraint=gpu
#SBATCH --gpus-per-node=1
#SBATCH --account=m2956_g

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Keep consistent with your current workflow.
source ~/.bashrc
conda activate /sdcc/u/gzhao/scratch/conda/inr_sampling
wandb offline

cd "$REPO_ROOT"

# W&B offline run tracking for later sync.
WANDB_BASE_DIR="${WANDB_DIR:-${REPO_ROOT}/coral/wandb}"
WANDB_RUN_DIR="${WANDB_BASE_DIR}/wandb"
mkdir -p "$WANDB_RUN_DIR"
SYNC_PATH_LOG="${REPO_ROOT}/wandb_sync_paths_compare-adaptive-topk-grid.txt"
echo "# Generated by compare-adaptive-topk-grid.sh on $(date)" > "$SYNC_PATH_LOG"
echo "# Format: run_name<TAB>offline_run_dir" >> "$SYNC_PATH_LOG"
echo "W&B sync path log: $SYNC_PATH_LOG"

# -----------------------------
# Baseline experiment settings
# -----------------------------
w0=30
sampling_rate=2e-3
train_ratio=1
inner_steps=6
lr=1e-4
depth=6
time_frame=100
re=10000
epochs=5000

data_path="/sdcc/u/gzhao/scratch/inr_sampling/data/NS2d/ns_data_res2048_re${re}_7.npy"

# -----------------------------
# Sweep knobs requested
# -----------------------------
adaptive_modes=("loss")
adaptive_iterations_list=(5)
# NOTE: config expects "poisson" spelling.
adaptive_count_modes=("same")
adaptive_topk_weight_modes=("area_over_count")

total_runs=$((${#adaptive_modes[@]} * ${#adaptive_iterations_list[@]} * ${#adaptive_count_modes[@]} * ${#adaptive_topk_weight_modes[@]}))
run_idx=0

echo "Starting adaptive sweep: ${total_runs} runs"

for adaptive_mode in "${adaptive_modes[@]}"; do
  for adaptive_iterations in "${adaptive_iterations_list[@]}"; do
    for count_mode in "${adaptive_count_modes[@]}"; do
      for topk_weight_mode in "${adaptive_topk_weight_modes[@]}"; do
        run_idx=$((run_idx + 1))

        run_name="NS1024_single_2d_grid_adaptive_re_${re}_sampling_${sampling_rate}_lr_${lr}_depth_${depth}_t${time_frame}_mode_${adaptive_mode}_it_${adaptive_iterations}_count_${count_mode}_topkw_${topk_weight_mode}"

        echo "[$run_idx/$total_runs] ${run_name}"

        before_runs="$(find "$WANDB_RUN_DIR" -maxdepth 1 -type d -name 'offline-run-*' -printf '%f\n' | sort)"

        python inr_sample/single_image_inr.py \
          data.dataset_name=NS \
          inr.model_type=siren \
          data.space_factor=1 \
          optim.batch_size=2 \
          optim.lr_inr=$lr \
          optim.epochs=$epochs \
          optim.inner_steps=$inner_steps \
          optim.evo_every_epochs=100 \
          inr.latent_dim=256 \
          inr.depth=$depth \
          inr.hidden_dim=155 \
          saved_checkpoint=False \
          wandb.name=$run_name \
          wandb.use_wandb=True \
          wandb.project=workshop-inr-sampling-revise \
          inr.w0=$w0 \
          sampling.type=2d_grid_adaptive \
          sampling.rate=$sampling_rate \
          sampling.adaptive_mode=$adaptive_mode \
          sampling.adaptive_iterations=$adaptive_iterations \
          sampling.adaptive_equal_cell_topk=True \
          sampling.adaptive_equal_cell_topk_count_mode=$count_mode \
          sampling.adaptive_equal_cell_topk_weight_mode=$topk_weight_mode \
          sampling.adaptive_weight_mode=none \
          sampling.adaptive_weight_value_eps=1e-6 \
          sampling.adaptive_weight_clip_ratio=10 \
          "data.split_ratios=[${train_ratio}, 0.01, 0.01]" \
          data.data_path=$data_path \
          data.data_type=other \
          data.single_time_frame=${time_frame}

        after_runs="$(find "$WANDB_RUN_DIR" -maxdepth 1 -type d -name 'offline-run-*' -printf '%f\n' | sort)"

        # Detect newly created offline run directories for this experiment.
        new_runs="$(comm -13 <(printf "%s\n" "$before_runs") <(printf "%s\n" "$after_runs") || true)"

        if [ -n "$new_runs" ]; then
          while IFS= read -r run_dir_name; do
            [ -z "$run_dir_name" ] && continue
            echo -e "${run_name}\t${WANDB_RUN_DIR}/${run_dir_name}" >> "$SYNC_PATH_LOG"
          done <<< "$new_runs"
        else
          # Fallback entry when automatic detection fails.
          echo -e "${run_name}\tNOT_FOUND" >> "$SYNC_PATH_LOG"
        fi
      done
    done
  done
done

echo "Adaptive sweep finished: ${run_idx} runs completed"
echo "W&B offline paths saved to: $SYNC_PATH_LOG"
