#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=2:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --constraint=gpu
#SBATCH --gpus-per-node=1
#SBATCH --account=m4259_g
set -eo pipefail

# -----------------------------
# Baseline experiment settings
# -----------------------------
w0=30
sampling_rate=2e-3
train_ratio=1
inner_steps=6
lr=1e-4
depth=6
time_frame=100
re=10000
epochs=5000

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

HOST=$(hostname -f)
is_bnl=false
if [[ $HOST == *"bnl"* ]]; then
  is_bnl=true
  source ~/.bashrc
  conda activate /sdcc/u/gzhao/scratch/conda/inr_sampling
  wandb offline
  wandb_base_dir="${WANDB_DIR:-${REPO_ROOT}/coral/wandb}"
  wandb_run_dir="$wandb_base_dir/wandb"
  offline_log_file="$wandb_base_dir/offline_run_paths.txt"
  mkdir -p "$wandb_run_dir"
  touch "$offline_log_file"
  SYNC_PATH_LOG="${REPO_ROOT}/outputs/wandb_sync_paths_compare_coefficient.txt"
  mkdir -p "$(dirname "$SYNC_PATH_LOG")"
  echo "# Generated by compare_coefficient.sh on $(date)" > "$SYNC_PATH_LOG"
  echo "# Format: run_name<TAB>offline_run_dir" >> "$SYNC_PATH_LOG"
  echo "W&B sync path log: $SYNC_PATH_LOG"
  data_path="/sdcc/u/gzhao/scratch/inr_sampling/data/NS2d/ns_data_res2048_re${re}_7.npy"
else
  source ~/anaconda3/etc/profile.d/conda.sh
  conda activate torchgeo
  data_path="/pscratch/sd/g/gzhao27/INR/INR_SAMPLE/data/NS2d/ns_data_res2048_re${re}_7.npy"

fi

cd "$REPO_ROOT"

# -----------------------------
# Sweep knobs for new coefficient
# -----------------------------
coefficient_list=(-0.3 -0.1 0.0 0.1 0.3 0.5 1.0)
adaptive_mode="loss"
adaptive_iterations=5
count_mode="same"
topk_weight_mode="area_over_count"

total_runs=${#coefficient_list[@]}
run_idx=0

echo "Starting coefficient sweep: ${total_runs} runs"

run_one() {
  local coef="$1"
  run_idx=$((run_idx + 1))

  run_name="NS1024_single_2d_grid_adaptive_re_${re}_sampling_${sampling_rate}_lr_${lr}_depth_${depth}_t${time_frame}_mode_${adaptive_mode}_it_${adaptive_iterations}_count_${count_mode}_topkw_${topk_weight_mode}_coef_${coef}"

  echo "[$run_idx/$total_runs] ${run_name}"

  if $is_bnl; then
    before_runs="$(find "$wandb_run_dir" -maxdepth 1 -type d -name 'offline-run-*' -printf '%f\n' | sort)"
  fi

  start_ts=$(date +%s)
  set +e
  python inr_sample/single_image_inr.py \
    data.dataset_name=NS \
    inr.model_type=siren \
    data.space_factor=1 \
    optim.batch_size=2 \
    optim.lr_inr=$lr \
    optim.epochs=$epochs \
    optim.inner_steps=$inner_steps \
    optim.evo_every_epochs=100 \
    inr.latent_dim=256 \
    inr.depth=$depth \
    inr.hidden_dim=155 \
    saved_checkpoint=False \
    wandb.name=$run_name \
    wandb.use_wandb=True \
    wandb.project=workshop-inr-sampling-revise \
    inr.w0=$w0 \
    sampling.type=2d_grid_adaptive \
    sampling.rate=$sampling_rate \
    sampling.adaptive_mode=$adaptive_mode \
    sampling.adaptive_iterations=$adaptive_iterations \
    sampling.adaptive_equal_cell_topk=True \
    sampling.adaptive_equal_cell_topk_count_mode=$count_mode \
    sampling.adaptive_equal_cell_topk_weight_mode=$topk_weight_mode \
    sampling.adaptive_equal_cell_topk_area_weight_coefficient=$coef \
    sampling.adaptive_weight_mode=none \
    sampling.adaptive_weight_value_eps=1e-6 \
    sampling.adaptive_weight_clip_ratio=10 \
    "data.split_ratios=[${train_ratio}, 0.01, 0.01]" \
    data.data_path=$data_path \
    data.data_type=other \
    data.single_time_frame=${time_frame}
  exit_code=$?
  set -e

  end_ts=$(date +%s)
  runtime_sec=$((end_ts - start_ts))

  if [ "$exit_code" -ne 0 ]; then
    echo "Run failed for coefficient=${coef} (exit=${exit_code}); continuing to next coefficient"
  fi

  if $is_bnl; then
    after_runs="$(find "$wandb_run_dir" -maxdepth 1 -type d -name 'offline-run-*' -printf '%f\n' | sort)"
    new_runs="$(comm -13 <(printf "%s\n" "$before_runs") <(printf "%s\n" "$after_runs") || true)"
    if [ -n "$new_runs" ]; then
      while IFS= read -r run_dir_name; do
        [ -z "$run_dir_name" ] && continue
        echo -e "${run_name}\t${wandb_run_dir}/${run_dir_name}" >> "$SYNC_PATH_LOG"
      done <<< "$new_runs"
    else
      echo -e "${run_name}\tNOT_FOUND" >> "$SYNC_PATH_LOG"
    fi
  fi
}

for coef in "${coefficient_list[@]}"; do
  run_one "$coef"
done

echo "Coefficient sweep finished: ${run_idx} runs completed"

if $is_bnl && [ -f "$SYNC_PATH_LOG" ]; then
  sync_script="${REPO_ROOT}/outputs/wandb_sync_compare_coefficient.sh"
  {
    echo "#!/bin/bash"
    echo "conda activate /sdcc/u/gzhao/scratch/conda/inr_sampling"
    echo ""
    while IFS=$'\t' read -r rname rpath; do
      [[ "$rname" == "#"* ]] && continue
      if [ "$rpath" = "NOT_FOUND" ]; then
        echo "# SKIPPED (not found): $rname"
      else
        echo "wandb sync \"$rpath\""
      fi
    done < "$SYNC_PATH_LOG"
  } > "$sync_script"
  chmod +x "$sync_script"
  echo "Sync script written to: $sync_script"
fi
